apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "weatherapi-6012"
    labels:
        app: "weatherapi-6012"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: weatherapi9856-weatherapi-6012.bc1e9f4b9eb743a1b7de.centralus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "weatherapi-6012"
                servicePort: 80