on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: weatherapiconntainer.azurecr.io
        username: ${{ secrets.acr_weatherapiconntainer_username }}
        password: ${{ secrets.acr_weatherapiconntainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t weatherapiconntainer.azurecr.io/weatherinformation:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push weatherapiconntainer.azurecr.io/weatherinformation:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_weatherinformation_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep weatherinformationa13f | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace weatherinformationa13f`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: weatherinformationa13f
        container-registry-url: weatherapiconntainer.azurecr.io
        container-registry-username: ${{ secrets.acr_weatherapiconntainer_username }}
        container-registry-password: ${{ secrets.acr_weatherapiconntainer_password }}
        secret-name: weatherinfordockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: weatherinformationa13f
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          weatherapiconntainer.azurecr.io/weatherinformation:${{ github.sha }}
        imagepullsecrets: |
          weatherinfordockerauth
